# fly.toml app configuration file generated for plane-club on 2024-10-16T09:52:12+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'plane-club'
primary_region = 'lhr'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[processes]
  app = ""
  queue = "php artisan queue:work --sleep=3 --tries=3 --timeout=3600"
  scheduler = "php artisan schedule:work"

[env]
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  APP_NAME='Plane Club'
  APP_TIMEZONE='UTC'
  APP_LOCALE='en'
  APP_FALLBACK_LOCALE='en'
  APP_FAKER_LOCALE='en_USss'
  APP_MAINTENANCE_DRIVER='file'
  BCRYPT_ROUNDS=12
  LOG_STACK='single'
  LOG_DEPRECATIONS_CHANNEL='null'
  DB_CONNECTION='pgsql'
  DB_QUEUE_CONNECTION='pgsql'
  DB_PORT=6543
  DB_DATABASE='postgres'
  SESSION_LIFETIME=120
  SESSION_ENCRYPT='false'
  SESSION_PATH='/'
  SESSION_DOMAIN='null'
  BROADCAST_CONNECTION='log'
  FILESYSTEM_DISK='s3'
  QUEUE_CONNECTION='database'
  CACHE_STORE='database'
  CACHE_PREFIX=''
  MAIL_MAILER='smtp'
  MAIL_HOST='live.smtp.mailtrap.io'
  MAIL_PORT=587
  MAIL_USERNAME='api'
  MAIL_PASSWORD='null'
  MAIL_ENCRYPTION='null'
  MAIL_FROM_ADDRESS="admin@planeclub.app"
  MAIL_FROM_NAME="Plane Club"
  AWS_DEFAULT_REGION='eu-west-2'
  AWS_BUCKET='plane-club'
  AWS_USE_PATH_STYLE_ENDPOINT='false'
  VITE_APP_NAME="${APP_NAME}"
  SENTRY_LARAVEL_DSN='https://aaf3ac941437e394431925c0507f5d68@o4507527015563264.ingest.de.sentry.io/4507527024083024'
  SENTRY_TRACES_SAMPLE_RATE=0.2
  CASHIER_CURRENCY='gbp'
  FFMPEG_BINARIES='/usr/bin/ffmpeg'
  FFPROBE_BINARIES='/usr/bin/ffprobe'
  FLY_APP_NAME='plane-club'
  FLY_QUEUE_MACHINE_ID='9080577c23e648'


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
  memory = '1gb'

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"
